# Generated by Django 4.2.3 on 2023-08-02 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='exercise',
        ),
    ]
